Print('ho3in senator kabir servers bogs')
Print('h//totr/u///tyyy/e.ori/')
Print('j/t//i')
Print('Ett/r//y')
Print('com2fi/l//tr')
Print('xccf//il/r4.il')
Print('vi/rs//fil/')
Print('fil/sent/kbr//f.ll/')
